# File config.ini - project variables

# ALLURE REPORT
allureReport=true

# BASE URL
baseUrl=https://api.trello.com/1
# If you want use string builder
baseUrlProtocol=https
baseUrlSubdomain=api
baseUrlDomain=trello
baseUrlTLD=com
baseUrlNumber=1
